### PR TITLE
Rename webapp to minifront

### PR DESCRIPTION
**Pull request by grod220**
Context: https://discord.com/channels/824484045370818580/1044457038886998137/1200144643321516032

Going to create a new web app in `/apps` https://github.com/penumbra-zone/web/issues/513

### CODE REVIEW

**Review by jessepinho — APPROVED** [review]
LGTM! I was thinking of taking the liberty of merging this myself so as to avoid rebase hell when other PRs get merged, but then I realized the other PRs would prob be harder to rebase after this change, than vice versa. So we can discuss Tue or Wed when is best to merge this?

**Comment by grod220** [comment]
Yep, can wait if there is a meaty PR we are waiting on to get merged first

**Comment by grod220** [comment]
Let's hang tight on adding more to this PR until the connection work is merged. I'm afraid it may only make it harder. I can continue this after the merge of the other stuff.

**Comment by grod220** [comment]
Was really confused, but it looks like the base branch changed. All good now.

**Comment by grod220** [comment]
Oh gosh, connected sites got mixed in. Nvm, need to blow this up.

**Pull request merged**
