### PR TITLE
RFC: styling the UI library

### PR DESCRIPTION
**Pull request by jessepinho**
This PR is a request for comments on the ADR I've written. Please read the ADR ([Markdown preview here](https://github.com/penumbra-zone/web/blob/04319e9a79347203f9eea19a5f7d0493dbe54878/docs/adrs/005-ui-library-css.md)), and make inline comments on the file or general comments here in the PR thread.

I've written the ADR as though it's a finished decision, but obviously it's not — I just wrote what my decision would be, as a starting point for the rest of the team to comment on it.

Since our web weekly tomorrow is canceled for July 4th, we'll need to talk about this issue asynchronously here in the PR. Perhaps we can come to a final decision at next Thursday's web weekly, if we haven't already resolved the issue here.

Related to https://github.com/prax-wallet/web/issues/81

### CODE REVIEW

**Comment by grod220** [comment]
It's really too bad there isn't some build tool that allows non-tailwind projects to use tailwind components. Given that's the case, I think the reasoning here makes sense.

The question then becomes, which css-in-js framework/method should we use? Ideas:

- Plain objects passed to `className` prop
- [styled-components](https://styled-components.com/)
- [emotion](https://emotion.sh/docs/introduction)
- [styled-jsx](https://github.com/vercel/styled-jsx)
- [linaria](https://github.com/callstack/linaria#documentation)
- [vanilla-extract](https://vanilla-extract.style/)

**Comment by VanishMax** [comment]
@grod220 @jessepinho Tailwind can be built just like any other solutions – by extracting CSS from JS, and consumers won't need to know about Tailwind existence. Take a look at the [vite-react-component-library-starter](https://github.com/rayyamhk/vite-react-component-library-starter) template, it builds into `index.js`, `index.d.ts`, and `index.css`. Theoretically, we could reconfigure it to build different components separately (not into one `index.js`) and have CSS being exported in chunks to reduce the styling load

**Comment by jessepinho** [comment]
@VanishMax we'd still run into the issues I've outlined [here](https://github.com/penumbra-zone/web/blob/04319e9a79347203f9eea19a5f7d0493dbe54878/docs/adrs/005-ui-library-css.md#cons-of-using-tailwind) — particularly the last one, where we'd either have to duplicate CSS classes across component CSS files, or we'd have to export a massive kitchen-sink CSS with a bunch of code that consumers don't need.

**Comment by VanishMax** [comment]
@jessepinho CSS chunks might solve the issue if configured correctly. Referencing your example, if three different Penumbra UI library components use `bg-card-radial`, then a chunk `abc1123xyz.chunk.css` file would be created and referenced by `1.css`, `2.css`, etc.

This is still a theory since I've done the same with JS chunks but not CSS but might be considered

**Comment by jessepinho** [comment]
@grod220 I could make a separate ADR/RFC for which framework to use, but I was personally leaning toward styled-components. It's the most popular one, and I've used it extensively in the past. However, `emotion` looks equally suited to the task.

Notes on the others:
- `styled-jsx` [requires a Babel plugin](https://github.com/vercel/styled-jsx?tab=readme-ov-file#getting-started). I'm a little unclear on whether that would be required for consumers as well, but I suspect it would, since it appears to modify the base definition of the `<style />` JSX component.
- `linaria` and `vanilla-extract` (clever name!) both compile CSS files, so they would still require consumers to import CSS files alongside our component JS files.
- Plain `style`* objects would give us the flexibility we need, but that basically means we're doing CSS-in-JS anyway, so we may as well use one of the established libraries like `emotion` or `styled-components`, IMO. 

\* You wrote "Plain objects passed to `className` prop" — I assume you meant the `style` prop?

**Review by grod220 — APPROVED** [review]
I believe styled-components had some issues with the new server components? Not sure, but we should ensure there's compatibility there with whatever we go with. It's a 👍 from me, but @VanishMax any further thoughts on this?

**Comment by jessepinho** [comment]
@grod220 hm, I'm not familiar with those issues, but I'm seeing support in [Remix](https://github.com/remix-run/examples/tree/main/styled-components) and [NextJS](https://nextjs.org/docs/app/building-your-application/styling/css-in-js#styled-components). Theoretically, we should probably discourage Penumbra UI consumers from doing server-side work anyway for privacy reasons, but 🤷🏻‍♂️

**Comment by VanishMax** [comment]
One important aspect I forgot to mention previously about the UI kit is the **accessibility**. Using Radix-ui helps us maintain quality across UI components in terms of the full keyboard support but we should not forget about the color contrast, HTML semantics and screen reader accessibility. 

Saying that, I propose we keep working with radix and possibly use some components from [react-aria](https://react-spectrum.adobe.com/react-aria/) (e.g. Calendar or DatePicker, which is not supported in Radix). 

Anyway, it doesn't relate to this RFC, just a thought. An approve from my side:)

**Review by VanishMax — APPROVED** [review]

**Comment by jessepinho** [comment]
Excellent call-out, @VanishMax — I definitely will be leaning on existing libraries more complex components like date pickers, calendars, etc. For simpler components, I'll likely roll them myself to avoid messy base style overrides, or I'll use headless UI libraries (like Radix, as you suggested) when needed.

**Pull request merged**
