### PR TITLE
Account for error where delegation was prepared for different epoch

### PR DESCRIPTION
**Pull request by jessepinho**
This should almost never happen. Basically, this should only happen when the user opens the web app in one epoch, then the epoch changes, then the user tries to delegate to a validator. In that case, we should at least show the error to the user rather than hanging indefinitely on "waiting for confirmation."

### CODE REVIEW

**Review by grod220 — DISMISSED** [review]
At some point, we need to loop back and re-think about how we are catching these tendermint errors. In fact, I think the API is likely flawed if we continue having to parse our own errors like this.

**Comment by grod220** [comment]
We've definitely been doing this incorrectly 😅 . Here's how it's handled in Rust:
https://github.com/penumbra-zone/penumbra/blob/aed1f8f607bfb4f9635d88f43b5ef8c5813036fd/crates/view/src/service.rs#L208-L218

Strange API, but if a non-zero response code is passed back, that indicates an error is present and viewable in the log.

```typescript
  async broadcastTx(tx: Transaction) {
    const params = tx.toBinary();
    // Note that "synchronous" here means "wait for the tx to be accepted by
    // the fullnode", not "wait for the tx to be included on chain.
    const { hash, log, code } = await this.client.broadcastTxSync({ params });

    // Non-zero response code indicates an error
    if (code !== 0n) {
      throw new Error(`Tendermint error ${code.toString()}: ${log}`);
    }
    return new TransactionId({ inner: hash });
  }
```

**Review by grod220 — APPROVED** [review]
Feel free to implement the change ⬆️  and merge

**Review by TalDerei — APPROVED** [review]

**Review by turbocrime — APPROVED** [review]

**Comment by jessepinho** [comment]
@grod220 good catch! I've updated this with your suggestion and I'll merge when it's green.

Heads-up that I also created tickets for [core](https://github.com/penumbra-zone/penumbra/issues/3961) and [minifront](https://github.com/penumbra-zone/web/issues/678) to use error codes for showing more helpful error messages when a transaction fails. Henry was saying that should come after mainnet, though.

**Pull request merged**
