### PR TITLE
Vite update

### PR DESCRIPTION
**Pull request by Vadim121197**

### CODE REVIEW

**Comment by Vadim121197** [comment]
what is the difference between pnpm build locally and github actions?

**Comment by Valentine1898** [comment]
It looks like the difference between local build and github actions build is in the handling of `Buffer -> buffer `cases

**Comment by Vadim121197** [comment]
I tried to find an analog of the buffer library, but buffer was updated 3 years ago! https://www.npmjs.com/package/buffer-lite tried to use this library and everything works! maybe you know another library?

**Comment by jessepinho** [comment]
Superseded by #391

**Pull request closed without merging**
