### PR TITLE
Beta extension deployment

### PR DESCRIPTION
**Pull request by grod220**
Closes https://github.com/penumbra-zone/web/issues/819

We now have a google group for prax beta testers: https://groups.google.com/a/penumbralabs.xyz/g/prax-beta-testers. This will allow us to push a private beta version of the extension, garner feedback from external contributors (i.e. passionate discord members). This serves as a kind of staging environment. Details of workflow in docs.

Note new colors for Beta extension.

Screenshot 2024-05-08 at 3 09 16 PM

### CODE REVIEW

**Comment by Valentine1898** [comment]
We probably need to have not only the beta version of extension, but also deploy the beta version of minifront. 
In fact, extension has very limited functionality, and there is almost nothing to test manually.  
At the same time, if you test beta version of extension with prod version of minifront, it may create non-existing bugs, and new functionality cannot be tested.

**Comment by grod220** [comment]
> but also deploy the beta version of minifront

Yep! Will create an issue for this. Should be quite easy to do.

**Review by Valentine1898 — APPROVED** [review]
LGTM

I wonder if it won't cause any conflicts when users have two wallet extensions installed (beta and prod) 
At least it is not obvious which extension will be used

**Comment by TalDerei** [comment]
Screenshot 2024-05-08 at 10 21 13 AM

oh you have to pay a registration fee, good revenue source there

**Review by TalDerei — APPROVED** [review]
what time window are we targeting between how long beta testers will have to review the beta extension features and when the production version will publish? Won't this create time-delays not only for new features, but also for fixes for recently discovered bugs? For the latter case, is there a way to manually publish the production version and bypass the review?

**Comment by grod220** [comment]
@TalDerei 

- Access to the chrome dev dashboard at the moment will be restricted to only a few internal team members fyi
- It's entirely up to us to determine how long we wish for our extension to be tested in the new "staging" step via this private beta extension. For hot fixes, we can always set the prod-version of the extension to go live immediately after approval (like we are doing now). But with the new beta version, we have more flexibility to test new features and/or chain upgrades before they go live for everyone.

**Pull request merged**
