### PR TITLE
update @radix-ui/react-dialog

### PR DESCRIPTION
**Pull request by zpoken**

### CODE REVIEW

**Review by grod220 — COMMENTED** [review]
Step 1 - update to latest version: `1.0.5`
Step 2 - Re-run the installer in the ui package: `npx shadcn-ui@latest add dialog`
Step 3 - Re-add the penumbra-specific styles if there were any
Step 4 - Test to ensure the UI still looks good

**Review by grod220 — APPROVED** [review]
I have noticed this PR and others are still using `merge`. Please do not use that anymore and only use rebase. It's too late for this pull request, you'll have to use merge again, but going forward please don't use merge.

**Comment by Vadim121197** [comment]
Rebase delete my code

**Comment by grod220** [comment]
You must be doing rebase wrong then. Please look up some tutorials. It cannot be done with pull requests that have done merge already. In the future, you should only use rebase.

**Pull request merged**
