### PR TITLE
IBC page styling changes

### PR DESCRIPTION
**Pull request by hdevalence**
I tinkered with the page layout a bit while pairing with @turbocrime on the substantive part (using cosmoskit).

Changes:

- Puts the IBC page first and calls it Shield Funds. The layout still needs further work, but it conveys a few things:
  - IBC is the first on the list of actions (users can't do anything until they transfer funds...)
  - The cosmos chain UI should be in light theme, while the rest of our UI is in a dark theme, indicating that it is different and has different properties
  
Screenshot 2024-03-20 at 6 04 04 PM

### CODE REVIEW

**Comment by hdevalence** [comment]
It would be nice to get some version of this merged in so that it doesn't get forgotten, could someone pick it up?

**Comment by TalDerei** [comment]
> It would be nice to get some version of this merged in so that it doesn't get forgotten, could someone pick it up?

think we discussed during web weekly that @turbocrime would pick it up.

**Comment by hdevalence** [comment]
Awesome!

**Comment by turbocrime** [comment]
hey, i did pick this up and work on it yesterday/today. sorry for low communication.

i'm working on the 'light' themed card for the ibc page, and implementing the background image in a correct way. our existing widgets make a lot of assumptions and aren't configurable so it's a surprising amount of work. will either finish or upload a wip today

**Comment by turbocrime** [comment]
#848 #849 #850 #851 #852 and more to achieve responsive layout and styleable components

**Comment by grod220** [comment]
Captured in https://github.com/penumbra-zone/web/pull/850

**Pull request closed without merging**
