### PR TITLE
custom grpcEndpoint migration

### LINKED ISSUE #963: v6.3.0 connection bug
There have been reports of users having syncing issues on v6.3.0. From @conorsch on [discord](https://discord.com/channels/824484045370818580/1044457038886998137/1230552679646888026):

```
today i was able to replicate the cannot-sync problem on the web extension, using v6.3.0 from the publishes releases. here's a screenshot of the browser console error message, and a searching string: "Could not establish connection. Receiving end does not exist."

this error occurred on a fresh launch of Google Chrome, with a previously installed extension version. to resolve, i tried several things that did not work:

1. restarting the browser
2. force-refreshing the page

i was able to "kick it" and restore syncing functionality, by—drum roll please—:

1. opening the rpc settings
2. confirming the default grpc.testnet.penumbra.zone was the only rpc endpoint configured
3. pressing the Save button on the rpc endpoints, even though i made no changes
4. waiting for countdown to restart, then force-refreshed the page.

i am uncertain whether the force-refresh in step 4 was required or not.

```
Screenshot 2024-04-19 at 2 50 56 PM

For minifront, this produces an "Penumbra extension unavailable" page.

### PR DESCRIPTION
**Pull request by Valentine1898**
Check out https://github.com/penumbra-zone/web/issues/963 before review 

That closes #963 and #993

It's important for us to fix #963 before the release, which will be Monday, so I propose such an ugly but simple solution, suggestions?

### CODE REVIEW

**Review by jessepinho — APPROVED** [review]
LGTM, but don't we have a system for migrating our local storage, so we could just make a migration the A) checks if `grpcEndpoint` is set, and B) sets it to the default if it's not already set?

If I'm mistaken though, ignore me and ship it :D

**Comment by Valentine1898** [comment]
> LGTM, but don't we have a system for migrating our local storage, so we could just make a migration the A) checks if `grpcEndpoint` is set, and B) sets it to the default if it's not already set?
> 
> If I'm mistaken though, ignore me and ship it :D

Here's why we can't do a system migration https://github.com/penumbra-zone/web/issues/963#issuecomment-2079781683

**Comment by jessepinho** [comment]
> > LGTM, but don't we have a system for migrating our local storage, so we could just make a migration the A) checks if `grpcEndpoint` is set, and B) sets it to the default if it's not already set?
> > If I'm mistaken though, ignore me and ship it :D
> 
> Here's why we can't do a system migration [#963 (comment)](https://github.com/penumbra-zone/web/issues/963#issuecomment-2079781683)

Yep, just saw that after I commented — my bad.

**Review by turbocrime — APPROVED** [review]
seems ok for now. eventually should be removed in favor of some error indication and instruction

**Pull request merged**
