### PR TITLE
view: audit action views

### PR DESCRIPTION
**Pull request by TalDerei**
References https://github.com/penumbra-zone/web/issues/1040

this spec is intended to inform what information should / should not be comprehended and exposed during signing a penumbra transaction. any suggestions regarding formatting the markdown file would be appreciated!

### CODE REVIEW

**Comment by TalDerei** [comment]
flagging the existing fields marked **visible** in this PR were meant to be marked as **opaque**, there was some naming confusion.

**Comment by TalDerei** [comment]
@hdevalence this spec is intended to inform what information should be comprehended during signing a penumbra transaction.  I remember you previously mentioned that the threshold custody in pcli has a subpar UI, requiring manually reviewing base64 json. How can we make this markdown file more extensible to improve this?

**Comment by TalDerei** [comment]
messaging reviewers if this sufficiently addresses the work scope proposed in #1040.

**Comment by TalDerei** [comment]
optimistically merging the ADR, async reviewers encouraged. this document can variably live in the web / core repos.

**Review by turbocrime — APPROVED** [review]

**Pull request merged**
