### PR TITLE
feat: loading spinner for assets table

### LINKED ISSUE #1381: Assets table status + streaming
Upon loading the assets table, two things are noticeable: 

1. There is not an indicator of loading status 
    - We should give visual indications of the loading (our classic spinner) & error statuses
2. All assets load at once
    - The `Balances` rpc method is a streaming one. This means, the client should receive assets as they come. It will also assist in the perceived responsiveness of the page if we didn't wait until all of them were loaded.

https://github.com/penumbra-zone/web/assets/16624263/1c21c7ef-55d4-46ac-b3b2-9f99825d40bd

### PR DESCRIPTION
**Pull request by vacekj**
re-fixes #1381

### CODE REVIEW

**Review by TalDerei — APPROVED** [review]

**Comment by TalDerei** [comment]
> More manual testing is needed, it seems to be loading my balances many times slower than before

seemed relatively performant to me during [testing](https://github.com/penumbra-zone/web/pull/1625#issuecomment-2265456799)?

**Comment by Valentine1898** [comment]
> > More manual testing is needed, it seems to be loading my balances many times slower than before
> 
> seemed relatively performant to me during [testing](https://github.com/penumbra-zone/web/pull/1625#issuecomment-2265456799)?

In the `penumbra-1` chain, my balances take ~21 sec to load 
don't merge this PR

**Comment by TalDerei** [comment]
can you add a changeset?

**Comment by TalDerei** [comment]
> > > More manual testing is needed, it seems to be loading my balances many times slower than before
> > 
> > 
> > seemed relatively performant to me during [testing](https://github.com/penumbra-zone/web/pull/1625#issuecomment-2265456799)?
> 
> In the `penumbra-1` chain, my balances take ~21 sec to load don't merge this PR

> > > More manual testing is needed, it seems to be loading my balances many times slower than before
> > 
> > 
> > seemed relatively performant to me during [testing](https://github.com/penumbra-zone/web/pull/1625#issuecomment-2265456799)?
> 
> In the `penumbra-1` chain, my balances take ~21 sec to load don't merge this PR

interesting, I didn't test `penumbra-1`

**Comment by Valentine1898** [comment]
https://github.com/user-attachments/assets/cfc80062-7894-425a-86a8-2a56ee3576a4

**Comment by vacekj** [comment]
@Valentine1898 ack, debugging..

**Comment by TalDerei** [comment]
following up on this, was the performance regression fixed?

**Comment by vacekj** [comment]
@VanishMax can you try to repro this? I can't seem to repro locally with the test account on mainnet.

**Comment by TalDerei** [comment]
> @VanishMax can you try to repro this? I can't seem to repro locally with the test account on mainnet.

I'll try to reproduce

**Comment by grod220** [comment]
I can't reproduce any slowness, but @JasonMHasperhoven can you test this out on testnet with the testnet whale seedphrase given you have an older macbook?

**Comment by TalDerei** [comment]
I can't reproduce the slowness either using the whale account on mainnet

**Comment by vacekj** [comment]
also can't see why the CI is failing but my local is passing - debugging now.

**Comment by JasonMHasperhoven** [comment]
Using testnet on my 2019 macbook:
https://github.com/user-attachments/assets/1f09cdaf-067e-42a8-8263-32d044f8bf1a

cc @grod220

**Comment by grod220** [comment]
> Using testnet on my 2019 macbook: https://github.com/user-attachments/assets/1f09cdaf-067e-42a8-8263-32d044f8bf1a

This is a compelling test. Why would streaming balances not be basically instant for a slower machine? The balances steps are this:

- Query notes from database
- Combine notes that are the same asset id + account
- Stream results back to the client
- React renders result (via ZQuery)

This leads me to believe there is a react rendering kind of performance drag.

@JasonMHasperhoven, another helpful test would be to make the same query on `main` and see how fast that is compared to this. If it's faster, that means it's a react rendering issue. If not, that means the rpc method (or db calls) in the extension is slower for lower performance machines.

**Comment by Valentine1898** [comment]
> Screen.Recording.2024-08-05.at.17.39.07.mov

Additional context 
I tested on my macbook m3 pro 
The mainnet wallet I tested on has about 3000 notes on it

**Comment by grod220** [comment]
Also @vacekj, just realized we want the spinner to be showing (in a place that doesn't block the content) during the entire stream lifetime. At the moment, it looks like it goes away after the first item is loaded. Can we also use [Linewave](https://github.com/penumbra-zone/web/blob/b732bc580e16d827e55d25a64b1d5d05d85b93a0/apps/node-status/src/components/header.tsx#L2) for the spinner (we use it in other places).

**Comment by vacekj** [comment]
@grod220 good point, will address this now.

**Comment by vacekj** [comment]
@grod220 addressed in the latest commit. the correct loading indicator will now show until the stream has finished.

**Comment by TalDerei** [comment]
still unclear if there's a performance regression?

**Comment by vacekj** [comment]
@TalDerei I can't replicate the perf regression on my machine, and don't see any obvious issues with code. Even with the perf. regression, this feels like better UX than before, so would carefully merge and watch for potential use reports.

Alternatively, I can try debugging with @JasonMHasperhoven on his machine to see what's wrong.

@grod220 would love your call here.

**Pull request merged**
