### PR TITLE
wasm refactor suggestions

### PR DESCRIPTION
**Pull request by turbocrime**
package structure, turbo, vitest without mocking wasm

### CODE REVIEW

**Comment by TalDerei** [comment]
Is there a reason for not differentiating between `@penumbra-zone/wasm-bundler` and `@penumbra-zone/wasm-nodejs` for dev and prod builds? Instead of `../crate/pkg`, can we alias that to something cleaner like `@penumbra-zone/wasm` instead of using a relative path?

**Comment by turbocrime** [comment]
differentiating between bundler and nodejs is unnecessary. i added some vitest config that understands how to load the wasm, and soon they'll support it natively without the plugin. had to fix a bunch of tests now that we're actually executing wasm instead of mocking it

**Comment by TalDerei** [comment]
all unit tests are passing on my end

Screenshot 2024-02-12 at 1 08 54 PM

**Review by TalDerei — APPROVED** [review]

**Comment by turbocrime** [comment]
it seems like vitest has some longstanding and unclear issues with 'browser mode' and its utils package, somehow interacting with pnpm, that are causing my error. not sure what to do about it

**Pull request merged**
