### PR TITLE
Update web for testnet63 changes

### PR DESCRIPTION
**Pull request by turbocrime**
addresses

* wasm crate version bump
* nct-sct rename penumbra-zone/penumbra@167e8e5d1eaee3d238f39de1646804647cde964a
* prefix change penumbra-zone/penumbra#1320

### CODE REVIEW

**Comment by hdevalence** [comment]
Screen Shot 2023-10-30 at 9 23 13 PM
Unsure if I'm not reloading the extension properly or if there's a bug here

**Comment by turbocrime** [comment]
`pnpm install` to make sure you're pulling the new wasm

remove, build, reinstall extension

**Comment by hdevalence** [comment]
I removed the extension entirely and reloaded it (thanks for the suggestion @turbocrime) and that error went away.

**Review by grod220 — APPROVED** [review]

**Comment by hdevalence** [comment]
I was able to make transactions!

**Pull request merged**
