### PR TITLE
disable the dex and ibc in minifront

### PR DESCRIPTION
**Pull request by TalDerei**
references https://github.com/penumbra-zone/web/issues/1454

cc @hdevalence the warning messages can probably be improved. 

Screenshot 2024-07-17 at 12 05 01 AM

### CODE REVIEW

**Comment by grod220** [comment]
Instead of a toast that shows up after they attempt an action, how about we just have a little banner at the top of the page with a message? Sort of like the red:
662957b844850e404d74288a_apple-website-notification-bar-1160x467

**Comment by TalDerei** [comment]
> Instead of a toast that shows up after they attempt an action, how about we just have a little banner at the top of the page with a message?

that's a good idea. I think we should also still display a toast with the friendlier error message, effectively disabling the functionality in the UI. Otherwise, the alternative is allowing transaction planning to occur and letting the transactions fail.

the only thing I was worried about is the banner possibly displaying when it shouldn't, given our weird sync behaviors?

**Comment by Valentine1898** [comment]
> the only thing I was worried about is the banner possibly displaying when it shouldn't, given our weird sync behaviors?

I think this can be avoided if we show banner only when `AppParameters` are available and only if `dexEnabled` is false

**Comment by TalDerei** [comment]
closing as out of scope for now, since changes happening in a week should capture this. If this is a desirable feature in the future, we can re-open.

**Pull request closed without merging**
