### PR TITLE
refactor: native wasm integration 

### PR DESCRIPTION
**Pull request by TalDerei**
References https://github.com/penumbra-zone/web/issues/218

### CODE REVIEW

**Comment by TalDerei** [comment]
@grod220 this represents preliminary work on porting the `penumbra-extension` to the web. Based on our discussion during the web sync, having local dependencies means we won't need to continue publishing NPM packages since local development would point to locally compiled dependencies. 

Regarding turborepo tooling considerations, I'm currently integrating the rust code into the build system and implementing sanity checking with sha256 hashing to verify we're using to the latest version.

**Comment by grod220** [comment]
Instead of putting the crate inside `src/` next to the typescript code, think we can have two main folders alongside each other: `packages/wasm/web/` and `packages/wasm/crate`.

We should drag over some of those helpers in `penumbra/crates/wasm/publish/run.ts` to help us compile as well. Given taht compiling takes so long, we shouldn't need to do it on every `pnpm build`. We should have a hash of the files in `packages/wasm/crate` saved somewhere and if there is a diff, we should throw an error, requiring the dev to re-compile and generate a new hash.

**Comment by turbocrime** [comment]
#492

**Comment by turbocrime** [comment]
CI is broken. lint now depends on presence of wasm output (d.ts files) and i've configured that in turbo.json but something in CI is failing.

**Comment by turbocrime** [comment]
also, since lint depends on wasm output, it would be cool if we could either

1) compile wasm once and forward that to other steps
2) have just one step that compiles wasm, then lints, then tests, then builds

**Comment by TalDerei** [comment]
Currently, necessary rust toolchain configs are missing from our yml files which seem to be the source of the failing CI workflows.

**Comment by TalDerei** [comment]
@turbocrime why are we nuking our existing CI? I was close to getting the CI to pass, and `.github/workflows/wasm.yml` was checking that the wasm crate builds cleanly and executed a full headless browser unit test which was removed.

**Comment by TalDerei** [comment]
Making a note here. While pairing with L, we decided to move the CI workflows into a single yml file with multiple jobs since `turbo-build, turbo-lint, and turbo-test` depend on the cache contents from executing `turbo-compile`. This simplifies our workflow succinctly.

**Comment by turbocrime** [comment]
:D

**Review by turbocrime — APPROVED** [review]

**Pull request merged**
