### PR TITLE
wip: new eslint rules and fix/ignore errors

### LINKED ISSUE #1668: Finalize eslint rules
Since https://github.com/penumbra-zone/web/pull/1461 we have todos collected in the [eslint config](https://github.com/penumbra-zone/web/blob/main/eslint.config.js). This task is to:

- Finalize rules that should be enabled
- Make fixes so CI/CD passes with enabled rules (likely multiple PRs)

Task:
- Choose whether to scrap or enable:
  - https://github.com/penumbra-zone/web/blob/main/eslint.config.js#L77 (probably should change to error)
  - https://github.com/penumbra-zone/web/blob/main/eslint.config.js#L87C10-L88
  - https://github.com/penumbra-zone/web/blob/main/eslint.config.js#L135-L141
  - https://github.com/penumbra-zone/web/blob/main/eslint.config.js#L180-L181 (probably can keep this)
  - https://github.com/penumbra-zone/web/blob/main/eslint.config.js#L180-L181
  - https://github.com/penumbra-zone/web/blob/main/eslint.config.js#L192-L212

Likely not all of these should be enabled, but I'd image many can.

### PR DESCRIPTION
**Pull request by vacekj**
fixes #1668 

I adjusted some rules as they felt unnecessarily restrictive for our usecase and added some rules to prevent misbehaviour and ease reviews.

Most of the checks are passing, but I rebased some commits recently so those might still need work.

### CODE REVIEW

**Review by TalDerei — APPROVED** [review]

**Comment by TalDerei** [comment]
should `no-non-null-assertion` rule be enabled?

**Review by turbocrime — CHANGES_REQUESTED** [review]
it seems like some of these rules are failing to apply. for example, by `@eslint-community/eslint-comments/require-description` these rules should be required to specify descriptions

https://github.com/penumbra-zone/web/blob/f585dbbf4d5b00e179561524cd7db2714714056e/packages/ui/src/PenumbraUIProvider/theme.ts#L278

https://github.com/penumbra-zone/web/blob/f585dbbf4d5b00e179561524cd7db2714714056e/packages/ui/src/AssetIcon/index.tsx#L27

**Review by turbocrime — APPROVED** [review]
going to unblock this so you don't have to wait on my re-review when addressing changes.

i would also like to use `@typescript-eslint/no-non-null-assertion` warnings.

**Comment by vacekj** [comment]
continuing with this @turbocrime

**Comment by vacekj** [comment]
@penumbra-zone/web-team requesting re-review on the latest commit - turned on no-non-null-assertions and ignored the existing errors

**Pull request merged**
