### PR TITLE
fix(minifront): #1391: display filled icon for the active auction

### LINKED ISSUE #1391: Auction icons positioning
Currently, as an auction is running, an icon indicates its status:

Screenshot 2024-07-01 at 3 56 12 PM

When it is fulfilled, currently, there is a green checked icon indicating its status to the user. 

Screenshot 2024-07-01 at 3 54 36 PM

**Task**: Instead of making the green check at the very end, place the checkmark at the position in which it was fulfilled. For example, if it were fulfilled 65% of the way through the auction, place the green checkmark 65% of the way across the width of the line.

### PR DESCRIPTION
**Pull request by VanishMax**
Closes #1391 

Shows the green checkmark icon for all filled dutch auctions

### CODE REVIEW

**Comment by grod220** [comment]
Can you show a screenshot of the new design?

**Comment by VanishMax** [comment]
@grod220 Unfortunately can't figure out how to run the dutch auction these days...

**Comment by Valentine1898** [comment]
> @grod220 Unfortunately can't figure out how to run the dutch auction these days...

You can create an auction in testnet (and probably in devnet too) if you manually set the **Maximum** and **Minimum** values for the auction. 

See the video from this issue (the bug is not related to this PR)
https://github.com/penumbra-zone/web/issues/1532

**Comment by VanishMax** [comment]
@Valentine1898 Thanks, I completely forgot that min and max are inputs. Hopefully will be changed soon with new designs.

Here's the screenshot that shows a green icon progressing towards the end of the auction

image

**Review by grod220 — APPROVED** [review]

**Pull request merged**
