### PR TITLE
don't bundle large video

### PR DESCRIPTION
**Pull request by turbocrime**
reduces bundle by 5mb

### CODE REVIEW

**Review by jessepinho — APPROVED** [review]
I actually was just noticing earlier today that we're not using this component anywhere. Feel free to delete the whole `hd-video.tsx` component file as well.

That said, note that any modern JS bundler will do "tree shaking" to get rid of unused code. So, since we're not using`<HdVideo />` anywhere, this file (and the mp4 it imports) was not getting included in our bundled code anyway.

**Comment by jessepinho** [comment]
Just saw your PR description — waaat?! OK, maybe I'm wrong.

**Comment by turbocrime** [comment]
yeah bundler config needs work

**Comment by grod220** [comment]
We actually have an issue with our "barrel" files (the ones that re-export to make imports look pretty). I've found they kinda nullify tree-shaking. It's hard to tell if it's our bundler's fault or the package itself. Worth exploring later though.

**Pull request merged**
