### PR TITLE
feat(ui): #1773, #1774:  `ValueInput` and `SwapInput`

### LINKED ISSUE #1773: Implement `<ValueInput/>` UI component
Design https://www.figma.com/design/WKgXSVVK3L0EI0sr9Hwjoa/penumbra-UI-library?node-id=1190-35102&node-type=CANVAS&m=dev

### LINKED ISSUE #1774: Implement `<SwapInput/>` UI component
Design https://www.figma.com/design/WKgXSVVK3L0EI0sr9Hwjoa/penumbra-UI-library?node-id=1190-33700&node-type=FRAME&m=dev

### LINKED ISSUE #1776: TextInput v2.1 update

### PR DESCRIPTION
**Pull request by VanishMax**
Closes #1773

Closes #1774 

Closes #1776

`ValueInput`: https://penumbra-ui-preview--pr1775-feat-1773-value-inp-ma6p3rle.web.app/?path=/docs/ui-library-valueinput--docs

`SwapInput`: https://penumbra-ui-preview--pr1775-feat-1773-value-inp-ma6p3rle.web.app/?path=/docs/ui-library-swapinput--docs

Also it updates the styles of `TextInput` and `Button` components to match the latest designs according to #1776.

image

image

### CODE REVIEW

**Review by grod220 — APPROVED** [review]
LGTM

**Review by TalDerei — APPROVED** [review]
LGTM. 

just to clarify, the white input range slider won't be displayed in production, right?

**Comment by TalDerei** [comment]
> @TalDerei Do you mean the arrows up-down in the number input? We can hide them but I don't see the necessity – it generally improves the a11y

It's a minor nit, but I personally feel like that component feels outdated and actually not that particularly useful when I was interacting with the [Storybook](https://penumbra-ui-preview--pr1775-feat-1773-value-inp-ma6p3rle.web.app/?path=/docs/ui-library-valueinput--docs). I'm in favor of removing it.

**Comment by VanishMax** [comment]
@TalDerei Hid the arrows

Won't merge this PR before #1771

image

**Pull request merged**
