### PR TITLE
feat: display block height in tx detail

### PR DESCRIPTION
**Pull request by vacekj**
fixes https://github.com/penumbra-zone/web/issues/1359

image

### CODE REVIEW

**Review by turbocrime — APPROVED** [review]
suggestion: it would be nice if the style matched (font style and color)

**Comment by turbocrime** [comment]
i wonder if we should make a practice of consistently displaying 'epoch' along with block height, maybe with a short notation.

**Comment by TalDerei** [comment]
we should keep the style consistent with the transaction hash. I'd also remove the 'in', and maybe you can experiment with encapsulating the block height in a small pill in the top right, like the memo field?

**Review by TalDerei — CHANGES_REQUESTED** [review]
we should keep the style consistent with the transaction hash. I'd also remove the 'in', and maybe you can experiment with encapsulating the block height in a small pill in the top right, similar to the memo field?

**Comment by vacekj** [comment]
@TalDerei addressed your feedback and used the pill.

**Review by TalDerei — APPROVED** [review]

**Pull request merged**
